apiVersion: configuration.konghq.com/v1beta1
kind: TCPIngress
metadata:
  name: echo-plaintext
  namespace: echo
  annotations:
    kubernetes.io/ingress.class: kong
spec:
  rules:
  - port: 5678
    backend:
      serviceName: http-echo
      servicePort: 5678
